### ISSUE TITLE
Problem installing GOverlay with MangoHUD

### ISSUE THREAD

**Issue by DemonExposer** [Klairm/Linux-Gaming-Setup#14]
```
jq - commandline JSON processor [version 1.6]

Usage:	jq [options] <jq filter> [file...]
	jq [options] --args <jq filter> [strings...]
	jq [options] --jsonargs <jq filter> [JSON_TEXTS...]

jq is a tool for processing JSON inputs, applying the given filter to
its JSON text inputs and producing the filter's results as JSON on
standard output.

The simplest filter is ., which copies jq's input to its output
unmodified (except for formatting, but note that IEEE754 is used
for number representation internally, with all that that implies).

For more advanced filters see the jq(1) manpage ("man jq")
and/or https://stedolan.github.io/jq

Example:

	$ echo '{"foo": 0}' | jq .
	{
		"foo": 0
	}

For a listing of options, use jq --help.
--2020-10-06 15:45:06--  http://null/
Ni solvigas null (null)... malsukceso: Dumtempa malsukceso ĉe nom-eltrovo.
wget: ne eblas trovi gastigantan adreson 'null'
Traceback (most recent call last):
  File "./GamingSetup.py", line 22, in <module>
    opt.disElec("programs")
  File "/home/kelvin/Linux-Gaming-Setup/options.py", line 24, in disElec
    pr.GOverlwMango("ubuntu")
  File "/home/kelvin/Linux-Gaming-Setup/programs.py", line 94, in GOverlwMango
    mHUDGOInst()		
  File "/home/kelvin/Linux-Gaming-Setup/programs.py", line 110, in mHUDGOInst
    mangoTarball = downloadTarball("flightlessmangom","MangoHud",2)
  File "/home/kelvin/Linux-Gaming-Setup/programs.py", line 210, in downloadTarball
    return tarball.split("/")[8]
IndexError: list index out of range
```

This is what I get when trying to install GOverlay with MangoHUD

**Comment by Klairm** [comment]
Fixed the error on the lastes commit, was a little typo on the code, sorry!
